/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro', 
      label: 'Welcome'
    },
    {
      type: 'category',
      label: 'Learn',
      collapsible: true,
      collapsed: false,
      items: [
        'learn/getting-started', 
        {
          type: 'category',
          label: 'Platforms',
          items: [
            'learn/platform/overview', 
            'learn/platform/avalanche-consensus', 
            'learn/platform/staking', 
            'learn/platform/transaction-fees'
          ],
        },
        {
          type: 'link',
          label: 'Blockchain Basic', // The link label
          href: 'https://support.avalabs.org/en/collections/2353492-blockchain-basics', // The external URL
        },
        {
          type: 'link',
          label: 'FAQ', // The link label
          href: 'https://support.avax.network/en/', // The external URL
        },
        'learn/avalanche-bridge-faq',
        {
          type: 'link',
          label: 'Forum', // The link label
          href: 'https://forum.avax.network/', // The external URL
        },
        {
          type: 'link',
          label: 'Ecosystem', // The link label
          href: 'https://ecosystem.avax.network/', // The external URL
        },
      ],
    },
    {
      type: 'category',
      label: 'Build',
      collapsible: true,
      items: [
        {
          type: 'category',
          label: 'Release Notes',
          items: [
            'build/release-notes/avalanchego', 
            {
              type: 'link',
              label: 'Email Alerts', // The link label
              href: 'http://eepurl.com/heNhSX', // The external URL
            },
          ],
        },
        {
          type: 'category',
          label: 'AvalancheGo APIs',
          items: [
            {
              type: 'autogenerated',
              dirName: 'build/avalanchego-apis',
            },
          ],
        },
        {
          type: 'category',
          label: 'References',
          items: [
            {
              type: 'autogenerated',
              dirName: 'build/references',
            },
          ],
        },
        {
          type: 'link',
          label: 'Whitepapers', // The link label
          href: 'https://www.avalabs.org/whitepapers', // The external URL
        },
        {
          type: 'link',
          label: 'Audits', // The link label
          href: 'https://github.com/ava-labs/audits', // The external URL
        }
      ],
    },
  ],
   
};

module.exports = sidebars;
